### ISSUE TITLE
Convert to Maven or gradle structure for larger audience, idea?

### ISSUE THREAD

**Issue by atomixnmc** [nguyenq/VietOCR3#8]
First of all, just to say hi and big thanks for your effort making this amazing software available for others to use.

I'm going to spend sometime converting this project to be more modern for larger audience. In fact i'm developing a smart vietnamese ocr product to run in pc and cloud. My fork will be in my account's github. 

My ideas:
- making this package downloadable and rerun able in any cloud environment. 
- use java-fx instead of swing
- extendable with plugin architecture. 

Any insight about that idea?

By the way, i'm Vietnamese too, if you think it's appropriate you can drop me a line via atomixnmc@gmail.com or skype: atomixnmc

**Comment by nguyenq** [comment]
Hi Cuong,

Any contribution to enhance the program in any way is always welcome, and appreciated by the general users.

A while back, I had developed a JavaFX version of the program, but out of the box, it did not look as good as the Swing version -- it probably needed more CSS styling -- and moreover, the standard TextArea control did not support highlights of non-contiguous text segments, making it not possible to mark misspelled words as a result of OCR inaccuracies. Because of those issues, I decided to shelve the project.

Upon receiving your ideas of improvements, I've dusted it off and just implemented some basic functionality. You may want to check it out over VietOCRfx project and see what needs to be done. TextArea probably can be replaced by another open-source text control that supports highlights. We can discuss further.

Best regards,
Quan

**Comment by atomixnmc** [comment]
Hi,

That's great, i will take a look at the current source code. I will continue the discussion in the other repository.

**Comment by nguyenq** [comment]
https://github.com/nguyenq/VietOCRfx/issues/1
